# Generated by Django 5.0.2 on 2024-04-05 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=20, verbose_name='Название альбома')),
                ('release_year', models.CharField(max_length=4, verbose_name='Год выпуска')),
                ('genre', models.CharField(max_length=20, verbose_name='Жанр')),
            ],
            options={
                'verbose_name': 'Альбом',
                'verbose_name_plural': 'Альбомы',
            },
        ),
        migrations.CreateModel(
            name='Performers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performer_name', models.CharField(max_length=30, verbose_name='Композитор')),
                ('performer_img', models.ImageField(blank=True, default=None, null=True, upload_to='tracks/performers/photo', verbose_name='Фото композитора')),
            ],
            options={
                'verbose_name': 'Композитор',
                'verbose_name_plural': 'Композиторы',
            },
        ),
        migrations.CreateModel(
            name='TrackList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_name', models.CharField(max_length=30, verbose_name='Название трека')),
                ('track_img', models.ImageField(blank=True, default=None, null=True, upload_to='tracks/albums/photo', verbose_name='Фото альбома')),
                ('genre', models.CharField(max_length=20, verbose_name='Жанр')),
                ('duration', models.CharField(max_length=10, verbose_name='Длительность')),
                ('album_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.album', verbose_name='Альбом')),
                ('performer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.performers', verbose_name='Композитор')),
            ],
            options={
                'verbose_name': 'Трек лист',
                'verbose_name_plural': 'Трек листы',
            },
        ),
        migrations.CreateModel(
            name='MyMusic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tracklist', verbose_name='Музыка')),
            ],
            options={
                'verbose_name': 'Моя музыка',
                'verbose_name_plural': 'Мои музыки',
            },
        ),
    ]
